SOLVER:
  BATCH_SIZE: 256
  LR: 0.0000299
  DA_LR: 0.00005884
DA:
  RANDOM_DIM: 128
  INIT_EPOCH: 16
DECODER:
  IN_DIM: 128
  HIDDEN_DIM: 128
  OUT_DIM: 256
PEPTIDE:
  EMBEDDING_DIM: 256
  NUM_FILTERS:
  - 128
  - 128
  - 128
PROTEIN:
  EMBEDDING_DIM: 512
  NUM_FILTERS:
  - 64
  - 64
  - 64
BCN:
  HEADS: 6
