SOLVER:
  BATCH_SIZE: 32
  LR: 0.00050421
  DA_LR: 0.00011662
DA:
  RANDOM_DIM: 128
  INIT_EPOCH: 10
DECODER:
  IN_DIM: 256
  HIDDEN_DIM: 256
  OUT_DIM: 128
PEPTIDE:
  EMBEDDING_DIM: 256
  NUM_FILTERS:
  - 64
  - 64
  - 64
PROTEIN:
  EMBEDDING_DIM: 256
  NUM_FILTERS:
  - 128
  - 128
  - 128
BCN:
  HEADS: 5
