SOLVER:
  BATCH_SIZE: 64
  LR: 0.00083821
  DA_LR: 0.0009539
DA:
  RANDOM_DIM: 128
  INIT_EPOCH: 19
DECODER:
  IN_DIM: 128
  HIDDEN_DIM: 256
  OUT_DIM: 128
PEPTIDE:
  EMBEDDING_DIM: 128
  NUM_FILTERS:
  - 64
  - 64
  - 64
PROTEIN:
  EMBEDDING_DIM: 512
  NUM_FILTERS:
  - 256
  - 256
  - 256
BCN:
  HEADS: 3
