SOLVER:
  BATCH_SIZE: 32
  LR: 0.00052757
  DA_LR: 0.00094525
DA:
  RANDOM_DIM: 256
  INIT_EPOCH: 16
DECODER:
  IN_DIM: 512
  HIDDEN_DIM: 128
  OUT_DIM: 512
PEPTIDE:
  EMBEDDING_DIM: 128
  NUM_FILTERS:
  - 64
  - 64
  - 64
PROTEIN:
  EMBEDDING_DIM: 512
  NUM_FILTERS:
  - 128
  - 128
  - 128
BCN:
  HEADS: 7
